### ISSUE TITLE
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM

### ISSUE THREAD

**Issue by wenwenyu** [mikevoets/jama16-retina-replication#5]
Hi,

I'm sorry about asking this, but I have no idea to solve this problem when run train.py. the following is error message:

# System information
- OS Platform and Distribution: Windows 10
- TensorFlow version: 1.2
- CUDA/cuDNN version:
- Cuda compilation tools, release 9.1 and cuDNN 8.0 with the NVIDIA Quadro M500M
- GPU memory: 2G
- Python version**: Python 3.6.2 |Anaconda 4.4.0 (64-bit)|

# Error Message:
Found GPU! Using channels first as default image data format.
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _do_call
    return fn(*args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,256,35,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: mixed0/concat = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](activation_5/Relu, activation_7/Relu, activation_10/Relu, activation_11/Relu, gradients/global_average_pooling2d/Mean_grad/Maximum_1/y)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: GradientDescent/update/_2290 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4395_GradientDescent/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\train.py", line 235, in <module>
    [global_step, mean_xentropy, train_op, update_brier])
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,256,35,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: mixed0/concat = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](activation_5/Relu, activation_7/Relu, activation_10/Relu, activation_11/Relu, gradients/global_average_pooling2d/Mean_grad/Maximum_1/y)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: GradientDescent/update/_2290 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4395_GradientDescent/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'mixed0/concat', defined at:
  File ".\train.py", line 133, in <module>
    include_top=False, weights='imagenet', pooling='avg', input_tensor=x)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\applications\inception_v3.py", line 216, in InceptionV3
    name='mixed0')
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\merge.py", line 665, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\merge.py", line 174, in call
    return self._merge_function(inputs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\merge.py", line 380, in _merge_function
    return K.concatenate(inputs, axis=self.axis)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py", line 2083, in concatenate
    return array_ops.concat([to_dense(x) for x in tensors], axis)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1175, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 777, in _concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "D:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,256,35,35] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: mixed0/concat = ConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](activation_5/Relu, activation_7/Relu, activation_10/Relu, activation_11/Relu, gradients/global_average_pooling2d/Mean_grad/Maximum_1/y)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: GradientDescent/update/_2290 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4395_GradientDescent/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by wenwenyu** [comment]
modify system information : TensorFlow version: 1.6

**Comment by wenwenyu** [comment]
Hi
I modify train_batch_size = 8  val_batch_size = 8  and shuffle_buffer_size = 32 then it works.

**Comment by mikevoets** [comment]
ResourceExhaustedError means that you should decrease the batch size. But you found that out already. I'll close this issue for now.
